# server port
server.port: 8081

# Keycloak Configuration
keycloak:
  credentials:
    secret: 2MehSx1FGixRYk1XdL44Gnsm6kAaFrcigKYYy5HxT2w
  auth-server-url: http://192.168.119.130:8080/auth
  realm: demo
  resource: democlient
  public-client: true
  principal-attribute: preferred_username
  redirect-rewrite-rules:
      pathOld: http://localhost:8081/callback

